template: live

sync:
- url: https://github.com/rancher/charts.git
  branch: dev-v2.5
  dropReleaseCandidates: true
- url: https://github.com/rancher/charts.git
  branch: dev-v2.6
  dropReleaseCandidates: true
helmRepo:
  cname: charts.rancher.io