annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: rancher-operator-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/release-name: rancher-operator-crd
apiVersion: v2
appVersion: 0.2.0-alpha
dependencies:
- condition: capi.enabled
  name: capi
  repository: ""
description: Rancher Operator CustomResourceDefinitions
name: rancher-operator-crd
version: 0.2.0-alpha03
