apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "windowsExporter.name" . }}-scripts
  namespace: {{ template "windowsExporter.namespace" . }}
  labels: {{ include "windowsExporter.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "scripts/*").AsConfig | indent 2 }}
