revision: "" # leave blank for no canary deployment, or set to given revision, eg: "1-7-2"
overlayFile: ""
tag: 1.6.6
installerVersion: 0.1.4

istiocoredns:
    enabled: false
    image:
      repository: coredns/coredns
      tag: 1.6.2
    pluginImage: istio/coredns-plugin:0.2-istio-1.1

base:
    enabled: true

cni:
    enabled: false

egressGateways:
    enabled: true
    type: NodePort

ingressGateways:
    enabled: true
    type: NodePort

istiodRemote:
    enabled: false

pilot:
    enabled: true
    image: pilot

policy:
    enabled: true
    image: mixer

telemetry:
    enabled: true
    image: mixer

sidecarInjectorWebhook:
  enableNamespacesByDefault: false
  objectSelector:
    enabled: true
    autoInject: true
  rewriteAppHTTPProbe: true

kiali:
  enabled: true
  # TODO: fix image below
  repository: rancher/kiali-kiali
  tag: v1.15
  contextPath: /
  dashboard:
    grafanaURL: http://monitoring-grafana.monitoring-system.svc
    auth:
      strategy: anonymous
  prometheusAddr: http://monitoring-rancher-monitor-prometheus.monitoring-system.svc:9090

global:
  proxy:
    image: proxyv2
  proxy_init:
    image: proxyv2
  curl:
    repository: rancher/pstauffer-curl
    tag: v1.0.3
  defaultNodeSelector: {}
  arch:
    amd64: 2
    s390x: 2
    ppc64le: 2
