kind: APIService
apiVersion: management.cattle.io/v3
metadata:
  name: rancher-operator-install
spec:
  secretName: steve-aggregation
  secretNamespace: {{.Release.Namespace}}
  paths:
  - /v3/connect/agent
  - /system-agent-install.sh
