apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-operator
spec:
  selector:
    matchLabels:
      app: rancher-operator
  template:
    metadata:
      labels:
        app: rancher-operator
    spec:
      containers:
      - env:
        - name: STAMP
          value: "{{.Values.stamp}}"
        - name: SKIP_CRDS
          value: "true"
        - name: ENABLE_CAPI
          value: "{{ .Values.capi.enabled }}"
        - name: ENABLE_RKE
          value: "{{ .Values.rke.enabled }}"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: '{{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        name: rancher-operator
        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
      serviceAccountName: rancher-operator
